#!/usr/bin/python2
# coding: utf-8

import fileinput
import csv
import sys
import argparse

#import osmapi

commitHelpMessage = "To import data in OpenStreetMap you must create a changeset. This script create a changeset, but we need a comment inside to explain the changeset, thus you must write your comment inside a file and give this file in argument"

commitFilename = "commit"
commit=""


parser = argparse.ArgumentParser()
parser.add_argument("filename", help="name of the csv file you wanna import. This file must have beeno generated by the mesure.py script.")

parser.add_argument("-c","--commitFileName", nargs=1, default="commit", action="store", dest="commitFilename", help=commitHelpMessage)

#api = osmapi.OsmApi()
#api = osmapi.OsmApi(api="https://api06.dev.openstreetmap.org", username = u"EPITA_BuggyProject", password = u"buggybuggy")
args = parser.parse_args()
nodeList = []

slopeAverageX = 0.0
slopeAverageY = 0.0

slopeX = ""
slopeY = ""

with open(commitFilename, 'r') as commitFile:
	commit=commitFile.read().replace('\n', ',')
	nodeID = 1
	#api.ChangesetCreate({u"comment": commit})
	with open(args.filename, 'r') as csvfile:
		spamreader = csv.reader(csvfile)
		for row in spamreader:
			lat = float(row[0])
			lon = float(row[1])
			rotX = float(row[2])
			rotY = float(row[3])
			#node=({u"id": -nodeID, u"lat": lat, u"lon": lon, u"tag": {u"slopeX" : rotX, u"slopeY" : rotY}})
			#createdNode = api.NodeCreate(node)
			#nodelist.append(createdNode)
			print "Creating node with ID = %d, lat = %f, lon = %f, slopeX = %f, slopeY = %f" % (-nodeID, lat, lon, rotX, rotY)
			slopeAverageX += rotX
			slopeAverageY += rotY
			nodeID += 1

		slopeAverageX /= nodeID
		slopeAverageY /= nodeID

		if slopeAverageX < 5.0:
			slopeX = "light"
		elif slopeAverageX < 10.0:
			slopeX = "medium"
		else:
			slopeX = "hard"

		if slopeAverageY < 5.0:
			slopeY = "light"
		elif slopeAverageY < 10.0:
			slopeY = "medium"
		else:
			slopeY = "hard"

		#wayData = ({u"nd": nodeList, u"tag" : {u"slopeX" : slopeX, u"slopeY" : slopeY}})
		#way = api.WayCreate(wayData)
		print "Creating way with slopeX = %s %f, slopeY = %s %f" % (slopeX,slopeAverageX,  slopeY, slopeAverageY)
	#api.ChangesetClose()
	print "Changeset created with comment = \"%s\"" % (commit)
